export const FACEBOOK_LOGIN_SUCCESS = "FACEBOOK_LOGIN_SUCCESS";
export const FACEBOOK_LOGIN_FAIL = "FACEBOOK_LOGIN_FAIL";
export const FETCH_RESTAURANT = "FETCH_RESTAURANT";
export const FETCH_RESTAURANTS = "FETCH_RESTAURANTS";
export const LIKE_RESTAURANT = "LIKE_RESTAURANT";
export const CLEAR_LIKED_RESTAURANTS = "CLEAR_LIKED_RESTAURANTS";
